# Generated by Django 5.0.14 on 2026-03-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Make a Difference Today', max_length=200)),
                ('quote', models.TextField(default='love for all , hate for none ...')),
                ('subtitle', models.TextField(default='Welcome to our platform designed to connect people through compassion and giving. Select your portal to proceed.')),
            ],
            options={
                'verbose_name_plural': 'Home Content',
            },
        ),
    ]
